import fredbuf
builder = fredbuf.TreeBuilder()
builder.accept("A\nB\nC\nD\nąćęłńóśżź")
tree = builder.create()
print(dir(tree))
print('length', tree.length(), tree.line_count(), tree.line_feed_count())
print('c@0=', tree.at(0), tree.at(1), tree.at(2))
print('l@0=', tree.line_at(0))
print('l[0]=', tree.get_line_content(1))
tree.insert(0, 'ĄĆĘŁŃÓŚŻŹ', False)
print('length', tree.length(), tree.line_count(), tree.line_feed_count())
print('c@0=', tree.at(0), tree.at(1), tree.at(2))
print('l@0=', tree.line_at(0))
print('l[0]=', tree.get_line_content(1))
line = 1
res = tree.get_line_range(line)
print(f"Line:{line} range: first={res.first} last={res.last}")
res = tree.get_line_range_crlf(line)
print(f"Line:{line} range: first={res.first} last={res.last}")
res = tree.get_line_range_with_newline(line)
print(f"Line:{line} range: first={res.first} last={res.last}")
data = tree.data()
print(data)
